# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.CharField(max_length=520)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='blogx_requests_created', to='tags.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='todo',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
