# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogx', '0002_auto_20161228_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_s', models.CharField(max_length=220)),
                ('description_s', models.CharField(max_length=520)),
                ('owner_s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags_s', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='blogx',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='blogx',
            name='tags',
        ),
        migrations.DeleteModel(
            name='blogx',
        ),
    ]
