# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
